In [1]:
# Common imports
import numpy as np
import pandas as pd
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import pickle
np.random.seed(1)

In [2]:
df = pd.read_csv('./RidingMowers.csv')
df.head(3)

   Income  Lot_Size Ownership
0    60.0      18.4     Owner
1    85.5      16.8     Owner
2    64.8      21.6     Owner

In [3]:
labelencoder = LabelEncoder()

df['Ownership'] = labelencoder.fit_transform(df['Ownership'])
df

    Income  Lot_Size  Ownership
0     60.0      18.4          1
1     85.5      16.8          1
2     64.8      21.6          1
3     61.5      20.8          1
4     87.0      23.6          1
5    110.1      19.2          1
6    108.0      17.6          1
7     82.8      22.4          1
8     69.0      20.0          1
9     93.0      20.8          1
10    51.0      22.0          1
11    81.0      20.0          1
12    75.0      19.6          0
13    52.8      20.8          0
14    64.8      17.2          0
15    43.2      20.4          0
16    84.0      17.6          0
17    49.2      17.6          0
18    59.4      16.0          0
19    66.0      18.4          0
20    47.4      16.4          0
21    33.0      18.8          0
22    51.0      14.0          0
23    63.0      14.8          0

In [4]:
X= df[['Income', 'Lot_Size']]
y=df['Ownership']

#train test split
X_train, X_test, y_train, y_test = train_test_split(X,y , test_size=0.30)

In [5]:
performance = pd.DataFrame({"model": [], "Accuracy": [], "Precision": [], "Recall": [], "F1": []})

In [6]:
svm_lin_model = SVC(kernel="linear", probability=True)
_ = svm_lin_model.fit(X_train, np.ravel(y_train))

In [7]:
model_preds = svm_lin_model.predict(X_test)
c_matrix = confusion_matrix(y_test, model_preds)
TP = c_matrix[1][1]
TN = c_matrix[0][0]
FP = c_matrix[0][1]
FN = c_matrix[1][0]
performance = pd.concat([performance, pd.DataFrame({'model':"linear svm", 
                                                    'Accuracy': [(TP+TN)/(TP+TN+FP+FN)], 
                                                    'Precision': [TP/(TP+FP)], 
                                                    'Recall': [TP/(TP+FN)], 
                                                    'F1': [2*TP/(2*TP+FP+FN)]
                                                     }, index=[0])])

In [8]:
svm_rbf_model = SVC(kernel="rbf", C=10, gamma='scale')
_ = svm_rbf_model.fit(X_train, np.ravel(y_train))

In [9]:
model_preds = svm_rbf_model.predict(X_test)
c_matrix = confusion_matrix(y_test, model_preds)
TP = c_matrix[1][1]
TN = c_matrix[0][0]
FP = c_matrix[0][1]
FN = c_matrix[1][0]
performance = pd.concat([performance, pd.DataFrame({'model':"rbf svm", 
                                                    'Accuracy': [(TP+TN)/(TP+TN+FP+FN)], 
                                                    'Precision': [TP/(TP+FP)], 
                                                    'Recall': [TP/(TP+FN)], 
                                                    'F1': [2*TP/(2*TP+FP+FN)]
                                                     }, index=[0])])

In [10]:
svm_poly_model = SVC(kernel="poly", degree=3, coef0=1, C=10, probability=True)
_ = svm_poly_model.fit(X_train, np.ravel(y_train))

In [11]:
model_preds = svm_poly_model.predict(X_test)
c_matrix = confusion_matrix(y_test, model_preds)
TP = c_matrix[1][1]
TN = c_matrix[0][0]
FP = c_matrix[0][1]
FN = c_matrix[1][0]
performance = pd.concat([performance, pd.DataFrame({'model':"poly svm", 
                                                    'Accuracy': [(TP+TN)/(TP+TN+FP+FN)], 
                                                    'Precision': [TP/(TP+FP)], 
                                                    'Recall': [TP/(TP+FN)], 
                                                    'F1': [2*TP/(2*TP+FP+FN)]
                                                     }, index=[0])])

In [12]:
performance.sort_values(by=['Accuracy'])

        model  Accuracy  Precision    Recall        F1
0     rbf svm     0.750   0.666667  0.666667  0.666667
0    poly svm     0.875   1.000000  0.666667  0.800000
0  linear svm     1.000   1.000000  1.000000  1.000000

In [13]:
pickle.dump(svm_lin_model, open('SVM_Linear_Model.pkl', 'wb'))